export class EntityStateCodes {
  static stateCodes = [
    {
      name: "ALABAMA",
      abbreviation: "AL",
      zoom: 7,
      latitude: 32.799,
      longitude: -86.8073,
    },
    {
      name: "ALASKA",
      abbreviation: "AK",
      zoom: 5,
      latitude: 61.385,
      longitude: -152.2683,
    },
    {
      name: "ARIZONA",
      abbreviation: "AZ",
      zoom: 7,
      latitude: 33.7712,
      longitude: -111.3877,
    },
    {
      name: "ARKANSAS",
      abbreviation: "AR",
      zoom: 7,
      latitude: 34.9513,
      longitude: -92.3809,
    },
    {
      name: "CALIFORNIA",
      abbreviation: "CA",
      zoom: 6,
      latitude: 36.17,
      longitude: -119.7462,
    },
    {
      name: "COLORADO",
      abbreviation: "CO",
      zoom: 7,
      latitude: 39.0646,
      longitude: -105.3272,
    },
    {
      name: "CONNECTICUT",
      abbreviation: "CT",
      zoom: 9,
      latitude: 41.5834,
      longitude: -72.7622,
    },
    {
      name: "DELAWARE",
      abbreviation: "DE",
      zoom: 9,
      latitude: 39.3498,
      longitude: -75.5148,
    },
    {
      name: "DISTRICT OF COLUMBIA",
      abbreviation: "DC",
      zoom: 11,
      latitude: 38.8974,
      longitude: -77.0268,
    },
    {
      name: "FLORIDA",
      abbreviation: "FL",
      zoom: 7,
      latitude: 27.8333,
      longitude: -81.717,
    },
    {
      name: "GEORGIA",
      abbreviation: "GA",
      zoom: 7,
      latitude: 32.9866,
      longitude: -83.6487,
    },
    {
      name: "HAWAII",
      abbreviation: "HI",
      zoom: 8,
      latitude: 21.1098,
      longitude: -157.5311,
    },
    {
      name: "IDAHO",
      abbreviation: "ID",
      zoom: 6,
      latitude: 44.2394,
      longitude: -114.5103,
    },
    {
      name: "ILLINOIS",
      abbreviation: "IL",
      zoom: 7,
      latitude: 40.3363,
      longitude: -89.0022,
    },
    {
      name: "INDIANA",
      abbreviation: "IN",
      zoom: 7,
      latitude: 39.8647,
      longitude: -86.2604,
    },
    {
      name: "IOWA",
      abbreviation: "IA",
      zoom: 7,
      latitude: 42.0046,
      longitude: -93.214,
    },
    {
      name: "KANSAS",
      abbreviation: "KS",
      zoom: 7,
      latitude: 38.5111,
      longitude: -96.8005,
    },
    {
      name: "KENTUCKY",
      abbreviation: "KY",
      zoom: 7,
      latitude: 37.669,
      longitude: -84.6514,
    },
    {
      name: "LOUISIANA",
      abbreviation: "LA",
      zoom: 7,
      latitude: 31.1801,
      longitude: -91.8749,
    },
    {
      name: "MAINE",
      abbreviation: "ME",
      zoom: 7,
      latitude: 44.6074,
      longitude: -69.3977,
    },
    {
      name: "MARYLAND",
      abbreviation: "MD",
      zoom: 8,
      latitude: 39.0724,
      longitude: -76.7902,
    },
    {
      name: "MASSACHUSETTS",
      abbreviation: "MA",
      zoom: 9,
      latitude: 42.2373,
      longitude: -71.5314,
    },
    {
      name: "MICHIGAN",
      abbreviation: "MI",
      zoom: 7,
      latitude: 43.3504,
      longitude: -84.5603,
    },
    {
      name: "MINNESOTA",
      abbreviation: "MN",
      zoom: 7,
      latitude: 45.7326,
      longitude: -93.9196,
    },
    {
      name: "MISSISSIPPI",
      abbreviation: "MS",
      zoom: 7,
      latitude: 32.7673,
      longitude: -89.6812,
    },
    {
      name: "MISSOURI",
      abbreviation: "MO",
      zoom: 7,
      latitude: 38.4623,
      longitude: -92.302,
    },
    {
      name: "MONTANA",
      abbreviation: "MT",
      zoom: 7,
      latitude: 46.9048,
      longitude: -110.3261,
    },
    {
      name: "NEBRASKA",
      abbreviation: "NE",
      zoom: 7,
      latitude: 41.1289,
      longitude: -98.2883,
    },
    {
      name: "NEVADA",
      abbreviation: "NV",
      zoom: 7,
      latitude: 38.4199,
      longitude: -117.1219,
    },
    {
      name: "NEW HAMPSHIRE",
      abbreviation: "NH",
      zoom: 8,
      latitude: 43.4108,
      longitude: -71.5653,
    },
    {
      name: "NEW JERSEY",
      abbreviation: "NJ",
      zoom: 8,
      latitude: 40.314,
      longitude: -74.5089,
    },
    {
      name: "NEW MEXICO",
      abbreviation: "NM",
      zoom: 7,
      latitude: 34.8375,
      longitude: -106.2371,
    },
    {
      name: "NEW YORK",
      abbreviation: "NY",
      zoom: 7,
      latitude: 42.1497,
      longitude: -74.9384,
    },
    {
      name: "NORTH CAROLINA",
      abbreviation: "NC",
      zoom: 7,
      latitude: 35.6411,
      longitude: -79.8431,
    },
    {
      name: "NORTH DAKOTA",
      abbreviation: "ND",
      zoom: 7,
      latitude: 47.5362,
      longitude: -99.793,
    },
    {
      name: "OHIO",
      abbreviation: "OH",
      zoom: 7,
      latitude: 40.3736,
      longitude: -82.7755,
    },
    {
      name: "OKLAHOMA",
      abbreviation: "OK",
      zoom: 7,
      latitude: 35.5376,
      longitude: -96.9247,
    },
    {
      name: "OREGON",
      abbreviation: "OR",
      zoom: 7,
      latitude: 44.5672,
      longitude: -122.1269,
    },
    {
      name: "PENNSYLVANIA",
      abbreviation: "PA",
      zoom: 7,
      latitude: 40.5773,
      longitude: -77.264,
    },
    {
      name: "PUERTO RICO",
      abbreviation: "PR",
      zoom: 10,
      latitude: 18.2491,
      longitude: -66.628,
    },
    {
      name: "RHODE ISLAND",
      abbreviation: "RI",
      zoom: 9,
      latitude: 41.6772,
      longitude: -71.5101,
    },
    {
      name: "SOUTH CAROLINA",
      abbreviation: "SC",
      zoom: 7,
      latitude: 33.8191,
      longitude: -80.9066,
    },
    {
      name: "SOUTH DAKOTA",
      abbreviation: "SD",
      zoom: 7,
      latitude: 44.2853,
      longitude: -99.4632,
    },
    {
      name: "TENNESSEE",
      abbreviation: "TN",
      zoom: 7,
      latitude: 35.7449,
      longitude: -86.7489,
    },
    {
      name: "TEXAS",
      abbreviation: "TX",
      zoom: 6,
      latitude: 31.106,
      longitude: -97.6475,
    },
    {
      name: "UTAH",
      abbreviation: "UT",
      zoom: 7,
      latitude: 40.1135,
      longitude: -111.8535,
    },
    {
      name: "VERMONT",
      abbreviation: "VT",
      zoom: 7,
      latitude: 44.0407,
      longitude: -72.7093,
    },
    {
      name: "VIRGINIA",
      abbreviation: "VA",
      zoom: 7,
      latitude: 37.768,
      longitude: -78.2057,
    },
    {
      name: "WASHINGTON",
      abbreviation: "WA",
      zoom: 7,
      latitude: 47.3917,
      longitude: -121.5708,
    },
    {
      name: "WEST VIRGINIA",
      abbreviation: "WV",
      zoom: 7,
      latitude: 38.468,
      longitude: -80.9696,
    },
    {
      name: "WISCONSIN",
      abbreviation: "WI",
      zoom: 7,
      latitude: 44.2563,
      longitude: -89.6385,
    },
    {
      name: "WYOMING",
      abbreviation: "WY",
      zoom: 7,
      latitude: 42.7475,
      longitude: -107.2085,
    },
  ];
}
